apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
- count: 4
  name: vote

images:
- name: schoolofdevops/vote
  newTag: v6

namespace: instavote

commonAnnotations:
  supported-by: sre@example.com

configMapGenerator:
- envs:
  - options.env
  name: vote-options

labels:
- includeSelectors: true
  pairs:
    env: staging
    project: instavote

patches:
- path: deployment.yaml
- path: service.yaml
